### ISSUE TITLE
Login with sshkey

### ISSUE THREAD

**Issue by mrelliot69** [TiBeN/CrontabManager#15]
Is it possible to login with x user and also use a sshkey associated with that user to authenticate?

$crontab_adapter = new TiBeN\CrontabManager\CrontabAdapter(user , sshkey ,true);

**Comment by TiBeN** [comment]
Hi mrelliot69,

I'm not sure what goal you have in mind: you want to be able to modify a crontab from another machine through SSH ?

**Comment by mrelliot69** [comment]
I want to have it on a machine, already tested but when i do the read of the crontab allways come empty, and i have crons on the crontab, so not sure why its not working.

Yeah, that was also one of the things that i wanted to do, be able to modify crons from other machines,...

**Comment by TiBeN** [comment]
Modify cron from user of other machines will never be possible inside the library because it has not been designed to that (It would involve a client/server scheme, networking capabilities etc.)

I think the issue you encounter is your PHP runtime (from where you run your code with the lib) is not run with the same user than the user your crontab is. If you are in a web environment (nginx, apache etc.), the runtime user is the one of the web server (typically `www-data`). That's why [supporting `sudo`](https://github.com/TiBeN/CrontabManager#work-with-the-crontab-of-another-user-than-runtime-user) was introduced.
